const inputNomeProduto = document.getElementById("nome-produto")
const inputDescricaoProduto = document.getElementById("descricao")
const inputLinkImagemProduto = document.getElementById("link-imagem")
const inputValorProduto = document.getElementById("preco")
const inputQuantidadeProduto = document.getElementById("quantidade")
const botaoCadastrarProduto = document.getElementById("cadastrar")
const formulario = document.getElementById("formulario")